################################################################################
#
# This work is all the original work of the author and is distributed under the
# GNU General Public License v3.0.
#
# Created By : Dulhan Jayalath
# Date : 2022/04/27
# Project : Real-time Neural Visual Navigation for Autonomous Off-Road Robots
#
################################################################################

# ------------------------------------------------------------------------------
# Converts a full tensorflow model into a tflite model
# Inputs:
# - model.hdf5 -> weights file generated by regional-cost-model/model.py
# Outputs:
# - model.tflite -> tflite model to be used on robot
#-------------------------------------------------------------------------------

import tensorflow as tf

# Generates a tflite model from a tensorflow model
def generate_tflite(model):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.allow_custom_ops = True
    tflite_model = converter.convert()

    with open('model.tflite', 'wb') as f:
        f.write(tflite_model)

if __name__ == "__main__":

    import os
    os.chdir('../regional-cost-model')
    from model import create_model
    os.chdir('../tflite-model')

    m = create_model()
    m.load_weights('model.hdf5')
    generate_tflite(m)